pull request for code review
AlekseySav/cc-formal pull request #1
Opened 2022-12-09 18:25 UTC by AlekseySav

2022-12-10 14:44 UTC, akhtyamovpavel requested changes
Добрый день!

Необходимо очень сильно дорабатывать код. Человек с улицы не сможет разобрать этот код - а тем более, добавить в него новый функционал. Попробуйте построить дерево вызовов функций и поймите, почему этот код сложно поддерживать

Буду ждать новую версию!

2022-12-10 14:44 UTC, akhtyamovpavel commented on Makefile
> +
Необходимо переделать под CMake

2022-12-10 14:44 UTC, akhtyamovpavel commented on examples/printf.c
> +    }
Почему однобуквенные переменные? Я ничего не понимаю

2022-12-10 14:44 UTC, akhtyamovpavel commented on examples/printf.c
> +            while (c = *str++)
Где фигурные скобки?

2022-12-10 14:44 UTC, akhtyamovpavel commented on include/lex.h
> +    std::queue<std::pair<int, lexvalue>> queue;
Давайте без пар

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/expr.cpp
> +    if (used_nodes == MAX_EXPR_NODES) fatal("expression overflow");
Фигурные скобки

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/expr.cpp
> +    expr_node* n = &node_pool[used_nodes++];
Что такое n?

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/expr.cpp
> +    sp--; // erase L_eof
Что такое `sp`?

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +void Program::define() {
Что мы определяем?

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +    }
Какой тип алгоритма используется? Если не LR, то у меня возникают вопросы по поводу этого практикума

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +        }
Серьезно? Во-первых, каждый тип токена - это отдельный класс. Во-вторых, необходимо все переписать при помощи паттерна Visitor

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +expr_tree Program::put_expr(expr_tree expr) {
Необходимо написать Visitor для генерации IR

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +            return type;
Без однобуквенных переменных, пожалуйста

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +                error("trying to dereference non-pointer variabled");
Не хотим специфицировать тип Exception?

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/symbol.cpp
> +        locals.push_back(name);
Фигурные скобки где?

2022-12-10 14:44 UTC, akhtyamovpavel commented on test/test-expr.cpp
> +    ASSERT_TRUE(TREE_EQ(parse.expr(), { num(1) }));
Это не Unit-тесты, а smoke-тесты. Если мы тестируем свой функционал, то необходимо реализовать unit-тесты (хотя бы для некоторого набора функций)

2022-12-10 14:44 UTC, akhtyamovpavel commented on src/program.cpp
> +int Program::declare(expr_tree expr, int size, symbol_type kind, bool local) {
Что мы декларируем?

2022-12-11 10:32 UTC, AlekseySav commented on examples/printf.c
> +    }
это же просто пример того, что можно написать, я где-то там комментарий оставлял, что переписал это из https://www.bell-labs.com/usr/dmr/www/kbman.html, просто заменил switch на if, т.к. switch не поддерживается, и добавил типы переменным

2022-12-11 10:37 UTC, AlekseySav commented on examples/printf.c
> +            while (c = *str++)
аналогично предыдущему, это просто пример, и это код из маунала, который я переделал немного, https://www.bell-labs.com/usr/dmr/www/kbman.html, в оригинале было
```c
while(c=char(x, j++)) != '*e')
			putchar(c);
```
соответственно условие цикла аналогично моему `c=*str++`

2022-12-11 10:46 UTC, AlekseySav commented on src/program.cpp
> +                error("trying to dereference non-pointer variabled");
error это не exception!! error просто выводит сообщение о том, что в файле есть ошибка, после него программа спокойно работает дальше, чтобы выводить остальные ошибки, которые найдет

2022-12-11 10:56 UTC, AlekseySav commented on src/expr.cpp
> +    sp--; // erase L_eof
stack pointer, мне кажется, это общепринятое сокращение (например, в ассеммблере и в интерпретаторе lua, sp означает stack pointer). Но могу в stack_top переименовать, например

2022-12-11 11:02 UTC, AlekseySav commented on src/program.cpp
> +    }
LR используется в парсинге expression-ов, для statement-ов не нужен парсер, там для каждого ключевого слова однозначно определяется, что должно идти дальше. Например, если мы считали while, то мы знаем, что statement имеет вид `while '(' expr ')' satement` и так далее

2023-02-04 12:33 UTC, merged